### ISSUE TITLE
Order status occasionally stays on pending payment

### ISSUE THREAD

**Issue by jordy2607** [MultiSafepay/magento2#70]
**Describe the bug**
After a customer placed an order and succesfully completed their payment and return the the shop some orders occasionally stay on the status pending payment. This happens a couple of time a week.

The invoice is created and the invoice email is send
The logging shows the order has been updated to processing, but the status is still pending payment. 
Also none of the saler_order invoice columns are updated, they stay on NULL.    

When we resend the notification from the MSP portal the order is updated correctly 

This does not happen on every order and i'm not able to find any errors or a change in the logs from which i can conclude something has gone wrong for these specific orders.

Maybe its a timing issue?

magento/product-community-edition: 2.4.5-p11
multisafepay/magento2: 3.9.1 
multisafepay/magento2-adminhtml:  1.31.1 
multisafepay/magento2-catalog-inventory: 1.0.3
multisafepay/magento2-core: 3.9.1  
multisafepay/magento2-frontend: 2.8.1 
multisafepay/php-sdk: 5.15.0 

**Expected behavior**
When a payment is successfull the order is always updated to the status processing and invoiced amounts are updated on the order.

**LOGS**

Order 000069037 stayed on pending payment after a succesfull payment and notification
Order 000069038 was updated to processing after a succesfull payment and notification

_I've removed sensitive data from the logs_

database data from the 2 orders
[data.csv](https://github.com/user-attachments/files/19685699/data.csv)

Server logs for order ID 000069037 **which stayed on status pending payment**

```
200	2025-04-10T10:14:28+00:00	POST /multisafepay/connect/notification?store_id=1&timestamp=1744280068&transactionid=000069037 HTTP/1.1
302	2025-04-10T10:14:49+00:00	GET /multisafepay/connect/success?secureToken=fad4da04beef7e2039f1e35d9cbd649bfef7a21eddf6ca55dfbfed8d524e6d33&transactionid=000069037 HTTP/1.1
200	2025-04-10T10:14:50+00:00	POST /multisafepay/connect/notification?store_id=1&timestamp=1744280088&transactionid=000069037 HTTP/1.1
302	2025-04-10T10:16:14+00:00	GET /multisafepay/connect/success?secureToken=fad4da04beef7e2039f1e35d9cbd649bfef7a21eddf6ca55dfbfed8d524e6d33&transactionid=000069037 HTTP/1.1
```

Debug logs for the same order

```
[2025-04-10T10:14:27.374341+00:00] MultiSafepay.INFO: (Order ID: 000069037): Payment URL is: https://pay.ideal.nl/transactions/https%3A%2F%2Ftx.ideal.nl%2F2%2FALW2P3E4XHUST25QF66HW5SZLNY?sig=BGBDAEIIAR6WLRLEST6XAH7S5B75IR2T2EWCF5JSWLUMQG23AYSUD5ZNVFVFQEIIAR4FCNN2C4DWYFCYU6MXUDMMX2XASOUDRZTAK4CNRBDQXPTDMPUUA [] []
[2025-04-10T10:14:28.170829+00:00] MultiSafepay.DEBUG: (POST notification) Headers: Cdn-Loop: Fastly
Fastly-Ff: KnylsTkayVNRVKOEtw/d9I2lv6I1M99/Puty5acJdr0=!AMS!cache-ams21060-AMS
Fastly-Magento-Vcl-Uploaded: 1.2.197
X-Varnish: 3262823909
Magento-Original-Url: /multisafepay/connect/notification?store_id=1&transactionid=000069037&timestamp=1744280068
Https: on
X-Timer: S1744280068.074184,VS0
X-Forwarded-Host: www.treasurejuwelier.nl
X-Forwarded-Server: cache-ams21060-AMS
X-Forwarded-For: 185.99.129.21
Fastly-Client-Ip: 185.99.129.21
Fastly-Ssl: 1
Content-Type: application/json
Auth: MTc0NDI4MDA2ODplMDFiZTA0NDRjMmIyNjMyM2E4MDg5MTc4ZWNiMDRhMmJiYzE1MmNkNTE0NTgxOTQ5ZjUyN2FjY2MyZGM4YTAxNTdiN2ZiZDFjYTY1NTJjOTNhNDc3YTUzOTY0MTAyZTY4MmFiMTlmMGU4OGI5NzlmNWE3MWFhM2U3ZDkwNGFkYg==
User-Agent: Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101")
Server: www
Accept: */*
Content-Length: 3544
Host: www.treasurejuwelier.nl
, Body: {"amount":111480,"amount_refunded":0,"checkout_options":{"alternate":[{"name":"21","rules":[{"country":"","rate":0.21}],"standalone":""},{"name":"-0","rules":[{"country":"","rate":0}],"standalone":""},{"name":"0","rules":[{"country":"","rate":0}],"standalone":""}],"default":[]},"costs":[{"amount":0.13,"description":"0.13 EUR For iDEAL Transactions","transaction_id":1079415313,"type":"SYSTEM"}],"created":"2025-04-10T12:14:27","currency":"EUR","custom_info":{"custom_1":null,"custom_2":null,"custom_3":null},"customer":{},"description":"Payment for order #000069037","fastcheckout":"NO","financial_status":"initialized","items":"<table border=\"0\" cellpadding=\"5\" width=\"100%\">\n<tr>\n<th width=\"10%\"><font size=\"2\" face=\"Verdana\">Quantity </font></th>\n<th align=\"left\"></th>\n<th align=\"left\"><font size=\"2\" face=\"Verdana\">Details </font></th>\n<th width=\"19%\" align=\"right\"><font size=\"2\" face=\"Verdana\">Price </font></th>\n</tr>\n<tr>\n<td align=\"center\"><font size=\"2\" face=\"Verdana\">1</font></td>\n<td width=\"6%\"></td>\n<td width=\"65%\"><font size=\"2\" face=\"Verdana\">THOJ0734 14k gouden anker schakelarmband 8,8 mm</font></td>\n<td align=\"right\">&euro;<font size=\"2\" face=\"Verdana\">929.75</font>\n</td>\n</tr>\n<tr>\n<td align=\"center\"><font size=\"2\" face=\"Verdana\">1</font></td>\n<td width=\"6%\"></td>\n<td width=\"65%\"><font size=\"2\" face=\"Verdana\">34 bonuspunten</font></td>\n<td align=\"right\">&euro;<font size=\"2\" face=\"Verdana\">-10.20</font>\n</td>\n</tr>\n<tr bgcolor=\"#E9F1F7\">\n<td colspan=\"3\" align=\"right\"><font size=\"2\" face=\"Verdana\">VAT:</font></td>\n<td align=\"right\">&euro;<font size=\"2\" face=\"Verdana\">195.25</font>\n</td>\n</tr>\n<tr bgcolor=\"#E9F1F7\">\n<td colspan=\"3\" align=\"right\"><font size=\"2\" face=\"Verdana\">Total:</font></td>\n<td align=\"right\">&euro;<font size=\"2\" face=\"Verdana\">1114.80</font>\n</td>\n</tr>\n</table>\n","modified":"2025-04-10T12:14:27","order_adjustment":{"total_adjustment":195.25,"total_tax":195.25},"order_id":"000069037","order_total":"1114.80","payment_details":{},"payment_methods":[],"reason":null,"reason_code":null,"related_transactions":null,"shopping_cart":{"items":[{"cashback":"","currency":"EUR","description":"Discount amount: 125","image":"","merchant_item_id":"59087_314672","name":"THOJ0734 14k gouden anker schakelarmband 8,8 mm","options":[],"product_url":"","quantity":1,"tax_table_selector":"21","unit_price":929.7520661157,"weight":{"unit":null,"value":null}},{"cashback":"","currency":"EUR","description":"34 bonuspunten","image":"","merchant_item_id":"aw_reward_points","name":"34 bonuspunten","options":[],"product_url":"","quantity":1,"tax_table_selector":"-0","unit_price":-10.2,"weight":{"unit":null,"value":null}}]},"status":"initialized","transaction_id":1744280067108804,"var1":"3.9.1","var2":null,"var3":null} [] []
[2025-04-10T10:14:28.197251+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: initialized): Notification process started [] []
[2025-04-10T10:14:28.943790+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: initialized): Order confirmation email after transaction has been sent [] []
[2025-04-10T10:14:28.947757+00:00] MultiSafepay.DEBUG: (Order ID: 000069037): Payment link comment added to the comment history [] []
[2025-04-10T10:14:28.973915+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: initialized): Order has been saved. [] []
[2025-04-10T10:14:29.012108+00:00] MultiSafepay.DEBUG: (Order ID: 000069037) User redirected to the following page: https://pay.ideal.nl/transactions/https%3A%2F%2Ftx.ideal.nl%2F2%2FALW2P3E4XHUST25QF66HW5SZLNY?sig=BGBDAEIIAR6WLRLEST6XAH7S5B75IR2T2EWCF5JSWLUMQG23AYSUD5ZNVFVFQEIIAR4FCNN2C4DWYFCYU6MXUDMMX2XASOUDRZTAK4CNRBDQXPTDMPUUA [] []
[2025-04-10T10:14:48.152960+00:00] MultiSafepay.DEBUG: (POST notification) Headers: Cdn-Loop: Fastly
Fastly-Ff: KnylsTkayVNRVKOEtw/d9I2lv6I1M99/Puty5acJdr0=!AMS!cache-ams2100144-AMS
Fastly-Magento-Vcl-Uploaded: 1.2.197
X-Varnish: 3258657974
Magento-Original-Url: /multisafepay/connect/notification?store_id=1&transactionid=000069037&timestamp=1744280088
Https: on
X-Timer: S1744280088.050613,VS0
X-Forwarded-Host: www.treasurejuwelier.nl
X-Forwarded-Server: cache-ams2100144-AMS
X-Forwarded-For: 185.99.129.21
Fastly-Client-Ip: 185.99.129.21
Fastly-Ssl: 1
Content-Type: application/json
Auth: MTc0NDI4MDA4ODozOGZlNTM5OTFhMDc2YmJjMTFlZmI2OWQ0MzkwZjU3NTdlZDY1YjFmZTg0N2ZjMmIyMzNkNGY5YjMxZjNhZjAzMjdlYjU4Y2FlNDViZmI5NTJiMTJlY2RhZjQwODBhODkyNTE4ZDJhYTYxMWRlZDY5OTI3ZjZhYTA3M2JjN2RhNg==
User-Agent: Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101")
Server: www
Accept: */*
Content-Length: 3768
Host: www.treasurejuwelier.nl
, Body: {"amount":111480,"amount_refunded":0,"checkout_options":{"alternate":[{"name":"21","rules":[{"country":"","rate":0.21}],"standalone":""},{"name":"-0","rules":[{"country":"","rate":0}],"standalone":""},{"name":"0","rules":[{"country":"","rate":0}],"standalone":""}],"default":[]},"completed":"2025-04-10T12:14:47","costs":[{"amount":0.13,"description":"0.13 EUR For iDEAL Transactions","transaction_id":1079415313,"type":"SYSTEM"}],"created":"2025-04-10T12:14:27","currency":"EUR","custom_info":{"custom_1":null,"custom_2":null,"custom_3":null},"customer":{},"description":"Payment for order #000069037","fastcheckout":"NO","financial_status":"completed","items":"<table border=\"0\" cellpadding=\"5\" width=\"100%\">\n<tr>\n<th width=\"10%\"><font size=\"2\" face=\"Verdana\">Quantity </font></th>\n<th align=\"left\"></th>\n<th align=\"left\"><font size=\"2\" face=\"Verdana\">Details </font></th>\n<th width=\"19%\" align=\"right\"><font size=\"2\" face=\"Verdana\">Price </font></th>\n</tr>\n<tr>\n<td align=\"center\"><font size=\"2\" face=\"Verdana\">1</font></td>\n<td width=\"6%\"></td>\n<td width=\"65%\"><font size=\"2\" face=\"Verdana\">THOJ0734 14k gouden anker schakelarmband 8,8 mm</font></td>\n<td align=\"right\">&euro;<font size=\"2\" face=\"Verdana\">929.75</font>\n</td>\n</tr>\n<tr>\n<td align=\"center\"><font size=\"2\" face=\"Verdana\">1</font></td>\n<td width=\"6%\"></td>\n<td width=\"65%\"><font size=\"2\" face=\"Verdana\">34 bonuspunten</font></td>\n<td align=\"right\">&euro;<font size=\"2\" face=\"Verdana\">-10.20</font>\n</td>\n</tr>\n<tr bgcolor=\"#E9F1F7\">\n<td colspan=\"3\" align=\"right\"><font size=\"2\" face=\"Verdana\">VAT:</font></td>\n<td align=\"right\">&euro;<font size=\"2\" face=\"Verdana\">195.25</font>\n</td>\n</tr>\n<tr bgcolor=\"#E9F1F7\">\n<td colspan=\"3\" align=\"right\"><font size=\"2\" face=\"Verdana\">Total:</font></td>\n<td align=\"right\">&euro;<font size=\"2\" face=\"Verdana\">1114.80</font>\n</td>\n</tr>\n</table>\n","modified":"2025-04-10T12:14:47","order_adjustment":{"total_adjustment":195.25,"total_tax":195.25},"order_id":"000069037","order_total":"1114.80","payment_details":{"recurring_flow":null,"recurring_id":null,"recurring_model":null,"type":"IDEAL"},"payment_methods":[{"amount":111480,"currency":"EUR","description":"Payment for order #000069037","external_transaction_id":"8151444266983464","payment_description":"iDEAL","status":"completed","type":"IDEAL"}],"reason":"SUCCESS","reason_code":null,"related_transactions":null,"shopping_cart":{"items":[{"cashback":"","currency":"EUR","description":"Discount amount: 125","image":"","merchant_item_id":"59087_314672","name":"THOJ0734 14k gouden anker schakelarmband 8,8 mm","options":[],"product_url":"","quantity":1,"tax_table_selector":"21","unit_price":929.7520661157,"weight":{"unit":null,"value":null}},{"cashback":"","currency":"EUR","description":"34 bonuspunten","image":"","merchant_item_id":"aw_reward_points","name":"34 bonuspunten","options":[],"product_url":"","quantity":1,"tax_table_selector":"-0","unit_price":-10.2,"weight":{"unit":null,"value":null}}]},"status":"completed","transaction_id":1744280067108804,"var1":"3.9.1","var2":null,"var3":null} [] []
[2025-04-10T10:14:49.121395+00:00] MultiSafepay.DEBUG: (Order ID: 000069037) User redirected to the success page. [] []
[2025-04-10T10:14:49.191990+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: completed): Notification process started [] []
[2025-04-10T10:14:49.192219+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: completed): MultiSafepay initialize Vault process has been started [] []
[2025-04-10T10:14:49.192423+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: completed): MultiSafepay initialize Vault process has ended [] []
[2025-04-10T10:14:49.193736+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: completed): MultiSafepay change payment process has been started [] []
[2025-04-10T10:14:49.193877+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: completed): MultiSafepay change payment process has ended [] []
[2025-04-10T10:14:49.194085+00:00] MultiSafepay.DEBUG: (Order ID: 000069037): Payment link comment already added to the comment history, skipping [] []
[2025-04-10T10:14:49.194213+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: completed): Order state has been changed to: processing [] []
[2025-04-10T10:14:49.274620+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: completed): Invoice created [] []
[2025-04-10T10:14:49.274716+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: completed): Order payment was updated [] []
[2025-04-10T10:14:49.279428+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: completed): Transaction saved [] []
[2025-04-10T10:14:49.279564+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: completed): Payment method is not a card payment method [] []
[2025-04-10T10:14:49.279623+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: completed): Order already has correct status, status not changed [] []
[2025-04-10T10:14:49.550097+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: completed): Order has been saved. [] []
[2025-04-10T10:14:50.250920+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: completed): Invoice e-mail has been sent [] []
[2025-04-10T10:14:50.353564+00:00] MultiSafepay.INFO: (Order ID: 000069037, PSP ID: 1744280067108804, Status: completed): Invoice: 000054460 update request has been sent to MultiSafepay. [] []
[2025-04-10T10:16:14.631103+00:00] MultiSafepay.DEBUG: (Order ID: 000069037) User redirected to the success page. [] []
```

Server logs for order ID 000069038 **which was updated to processing**

```
200	2025-04-10T11:16:47+00:00	POST /multisafepay/connect/notification?store_id=1&timestamp=1744283806&transactionid=000069038 HTTP/1.1
302	2025-04-10T11:17:45+00:00		GET /multisafepay/connect/success?secureToken=d205f19dee43b73095cf7ac60f29d078b69b141fe9ecf6877afdc3e8dfdbf942&transactionid=000069038 HTTP/1.1
200	2025-04-10T11:17:47+00:00		POST /multisafepay/connect/notification?store_id=1&timestamp=1744283865&transactionid=000069038 HTTP/1.1
```

Debug logs for the same order

```
[2025-04-10T11:16:31.870402+00:00] MultiSafepay.INFO: (Order ID: 000069038): Payment URL is: https://payv2.multisafepay.com/connect/2045PCcIilAwMs5uBt6Q6YDEWIp4ZVHyQV3/?lang=nl_NL [] []
[2025-04-10T11:16:32.366781+00:00] MultiSafepay.DEBUG: (Order ID: 000069038) User redirected to the following page: https://payv2.multisafepay.com/connect/2045PCcIilAwMs5uBt6Q6YDEWIp4ZVHyQV3/?lang=nl_NL [] []
[2025-04-10T11:16:46.478169+00:00] MultiSafepay.DEBUG: (POST notification) Headers: Cdn-Loop: Fastly
Fastly-Ff: KnylsTkayVNRVKOEtw/d9I2lv6I1M99/Puty5acJdr0=!AMS!cache-ams21033-AMS
Fastly-Magento-Vcl-Uploaded: 1.2.197
X-Varnish: 909638528
Magento-Original-Url: /multisafepay/connect/notification?store_id=1&transactionid=000069038&timestamp=1744283806
Https: on
X-Timer: S1744283806.281488,VS0
X-Forwarded-Host: www.treasurejuwelier.nl
X-Forwarded-Server: cache-ams21033-AMS
X-Forwarded-For: 185.99.129.21
Fastly-Client-Ip: 185.99.129.21
Fastly-Ssl: 1
Content-Type: application/json
Auth: MTc0NDI4MzgwNjplYmJhMGJiN2E3YWY3NzA5ZmY3NmZiOTlhZjA5OTBiYzE1NWY0ZWM3OTE5MTk3NGJjNjgzMjQ1MmFhZWIwOTM5YThlNzc0MWFhZTExMjhjZDU2MjI3NmJjOGM4YWIxNjZiZWE2YThkZWQ5NWYzYjJjZDUyYjc1MjUxMDMyNmQyMg==
User-Agent: Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101")
Server: www
Accept: */*
Content-Length: 2831
Host: www.treasurejuwelier.nl
, Body: {"amount":32400,"amount_refunded":0,"checkout_options":{"alternate":[{"name":"21","rules":[{"country":"","rate":0.21}],"standalone":""},{"name":"0","rules":[{"country":"","rate":0}],"standalone":""}],"default":[]},"costs":[{"amount":5.02,"description":"1.55 % For MasterCard Transactions","transaction_id":1079466006,"type":"SYSTEM"}],"created":"2025-04-10T13:16:42","currency":"EUR","custom_info":{"custom_1":null,"custom_2":null,"custom_3":null},"customer":{},"description":"Payment for order #000069038","fastcheckout":"NO","financial_status":"initialized","items":"<table border=\"0\" cellpadding=\"5\" width=\"100%\">\n<tr>\n<th width=\"10%\"><font size=\"2\" face=\"Verdana\">Quantity </font></th>\n<th align=\"left\"></th>\n<th align=\"left\"><font size=\"2\" face=\"Verdana\">Details </font></th>\n<th width=\"19%\" align=\"right\"><font size=\"2\" face=\"Verdana\">Price </font></th>\n</tr>\n<tr>\n<td align=\"center\"><font size=\"2\" face=\"Verdana\">1</font></td>\n<td width=\"6%\"></td>\n<td width=\"65%\"><font size=\"2\" face=\"Verdana\">SUR373P1 Titanium herenhorloge 40,2 mm</font></td>\n<td align=\"right\">&euro;<font size=\"2\" face=\"Verdana\">267.77</font>\n</td>\n</tr>\n</table>\n","modified":"2025-04-10T13:16:44","order_adjustment":{"total_adjustment":56.231404958673,"total_tax":56.231404958673},"order_id":"000069038","order_total":323.999999999973,"payment_details":{},"payment_methods":[],"reason":null,"reason_code":null,"related_transactions":null,"shopping_cart":{"items":[{"cashback":"","currency":"EUR","description":"Discount amount: 36","image":"","merchant_item_id":"55102_314677","name":"SUR373P1 Titanium herenhorloge 40,2 mm","options":[],"product_url":"","quantity":1,"tax_table_selector":"21","unit_price":267.7685950413,"weight":{"unit":null,"value":null}}]},"status":"initialized","transaction_id":1744283802109052,"var1":"3.9.1","var2":null,"var3":null} [] []
[2025-04-10T11:16:46.495230+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: initialized): Notification process started [] []
[2025-04-10T11:16:47.131194+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: initialized): Order confirmation email after transaction has been sent [] []
[2025-04-10T11:16:47.134425+00:00] MultiSafepay.DEBUG: (Order ID: 000069038): Payment link comment added to the comment history [] []
[2025-04-10T11:16:47.159752+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: initialized): Order has been saved. [] []
[2025-04-10T11:17:15.914695+00:00] MultiSafepay.INFO: (Order ID: 000069032): The shipping status has been updated at MultiSafepay [] []
[2025-04-10T11:17:45.273336+00:00] MultiSafepay.DEBUG: (Order ID: 000069038) User redirected to the success page. [] []
[2025-04-10T11:17:45.283096+00:00] MultiSafepay.DEBUG: (POST notification) Headers: Cdn-Loop: Fastly
Fastly-Ff: KnylsTkayVNRVKOEtw/d9I2lv6I1M99/Puty5acJdr0=!AMS!cache-ams2100102-AMS
Fastly-Magento-Vcl-Uploaded: 1.2.197
X-Varnish: 635194970
Magento-Original-Url: /multisafepay/connect/notification?store_id=1&transactionid=000069038&timestamp=1744283865
Https: on
X-Timer: S1744283865.186936,VS0
X-Forwarded-Host: www.treasurejuwelier.nl
X-Forwarded-Server: cache-ams2100102-AMS
X-Forwarded-For: 185.99.129.21
Fastly-Client-Ip: 185.99.129.21
Fastly-Ssl: 1
Content-Type: application/json
Auth: MTc0NDI4Mzg2NTowYTZiZTYyNzE4OGM5OTg5NTk4NDRlZjUzZjRiOTFiYjRhNDY0ZmFjOTBkYTRmNDI3N2U0YmMwMjRlZDc5MmQ3MjFiMTExYTQ1OGQwMzQ5N2YxNmExYzNhNTY1ZTUxOTZkMWEwNTg0ZTIyYjZkOTY3MGJmYzY4MjBhMTBkYWQ1NQ==
User-Agent: Mozilla/5.0 (X11; Debian; Linux x86_64; rv:33.0) Gecko/20100101")
Server: www
Accept: */*
Content-Length: 3145
Host: www.treasurejuwelier.nl
, Body: {"amount":32400,"amount_refunded":0,"checkout_options":{"alternate":[{"name":"21","rules":[{"country":"","rate":0.21}],"standalone":""},{"name":"0","rules":[{"country":"","rate":0}],"standalone":""}],"default":[]},"completed":"2025-04-10T13:17:42","costs":[{"amount":5.02,"description":"1.55 % For MasterCard Transactions","transaction_id":1079466006,"type":"SYSTEM"}],"created":"2025-04-10T13:16:42","currency":"EUR","custom_info":{"custom_1":null,"custom_2":null,"custom_3":null},"customer":{},"description":"Payment for order #000069038","fastcheckout":"NO","financial_status":"completed","items":"<table border=\"0\" cellpadding=\"5\" width=\"100%\">\n<tr>\n<th width=\"10%\"><font size=\"2\" face=\"Verdana\">Quantity </font></th>\n<th align=\"left\"></th>\n<th align=\"left\"><font size=\"2\" face=\"Verdana\">Details </font></th>\n<th width=\"19%\" align=\"right\"><font size=\"2\" face=\"Verdana\">Price </font></th>\n</tr>\n<tr>\n<td align=\"center\"><font size=\"2\" face=\"Verdana\">1</font></td>\n<td width=\"6%\"></td>\n<td width=\"65%\"><font size=\"2\" face=\"Verdana\">SUR373P1 Titanium herenhorloge 40,2 mm</font></td>\n<td align=\"right\">&euro;<font size=\"2\" face=\"Verdana\">267.77</font>\n</td>\n</tr>\n</table>\n","modified":"2025-04-10T13:17:42","order_adjustment":{"total_adjustment":56.231404958673,"total_tax":56.231404958673},"order_id":"000069038","order_total":323.999999999973,"payment_details":{},"payment_methods":[],"reason":"Approved","reason_code":"1000","related_transactions":null,"shopping_cart":{"items":[{"cashback":"","currency":"EUR","description":"Discount amount: 36","image":"","merchant_item_id":"55102_314677","name":"SUR373P1 Titanium herenhorloge 40,2 mm","options":[],"product_url":"","quantity":1,"tax_table_selector":"21","unit_price":267.7685950413,"weight":{"unit":null,"value":null}}]},"status":"completed","transaction_id":1744283802109052,"var1":"3.9.1","var2":null,"var3":null} [] []
[2025-04-10T11:17:46.311980+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: completed): Notification process started [] []
[2025-04-10T11:17:46.312189+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: completed): MultiSafepay initialize Vault process has been started [] []
[2025-04-10T11:17:46.313113+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: completed): MultiSafepay initialize Vault process has ended [] []
[2025-04-10T11:17:46.314356+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: completed): MultiSafepay change payment process has been started [] []
[2025-04-10T11:17:46.314498+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: completed): MultiSafepay change payment process has ended [] []
[2025-04-10T11:17:46.314624+00:00] MultiSafepay.DEBUG: (Order ID: 000069038): Payment link comment already added to the comment history, skipping [] []
[2025-04-10T11:17:46.314720+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: completed): Order state has been changed to: processing [] []
[2025-04-10T11:17:46.400242+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: completed): Invoice created [] []
[2025-04-10T11:17:46.400337+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: completed): Order payment was updated [] []
[2025-04-10T11:17:46.405218+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: completed): Transaction saved [] []
[2025-04-10T11:17:46.405346+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: completed): Payment method is not a card payment method [] []
[2025-04-10T11:17:46.405411+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: completed): Order already has correct status, status not changed [] []
[2025-04-10T11:17:46.688478+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: completed): Order has been saved. [] []
[2025-04-10T11:17:47.474929+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: completed): Invoice e-mail has been sent [] []
[2025-04-10T11:17:47.581995+00:00] MultiSafepay.INFO: (Order ID: 000069038, PSP ID: 1744283802109052, Status: completed): Invoice: 000054461 update request has been sent to MultiSafepay. [] []
```

**Comment by vinodsowdagar** [comment]
Hi @jordy2607 ,

Thanks for the information. We'll look into it as soon as possible and come back to you later.

**Comment by jordy2607** [comment]
Hi @vinodsowdagar 

Do you have an update?

**Comment by vinodsowdagar** [comment]
Hi @jordy2607 ,

Based on your logs everything seems to be fine. We think this might be caused by another module that hooks into the invoice creation or order save process and overwrites the order again into a previous state. Do you have an idea about which module this could be?

In the meantime we are trying to figure out a way to prevent this, but it is a currently ongoing investigation which will take a bit more time.

We will keep you updated about the progress.

**Comment by jordy2607** [comment]
Hi @vinodsowdagar 

Apologies for the delayed response. I've looked through all modules installed, but there aren't many third party modules which hook into order processing processes. Except for MyParcelNL_Magento, but as far as i can see this module doesn't seem to interfere with order states.

"myparcelnl/magento": "4.8.1",
"myparcelnl/sdk": "7.6.0",

**Comment by davejuist** [comment]
@vinodsowdagar we installed the latest version but this issue still occurs. If a customer checks out as guest, chooses card payment, then created a account after login the order stays on pending payment, eventhough you see the captured notifications with status going to processing in the comments.

**Comment by danielcivit** [comment]
Hi @davejuist 

- Thanks for your input. 
- The issue we fixed on the latest release, was related to a specific feature in Amasty Checkout. 
- I wonder how and where did you enable a feature where "If a customer checks out as guest, chooses card payment, then **created a account after login**".

**Comment by davejuist** [comment]
@danielcivit we also use Amasty Checkout, but updating didn't fix the issue. We don't use the option "Let Customers Create an Account at Checkout", but we see it happens on guest orders that don`t have a account, or created a account afterwards. So apologies for the confusion. Seems the mentioned case in the changelog is a separate issue

We also see orders that actually get the status cancelled eventhough notification was set to processing and the invoice was created.

**Comment by danielcivit** [comment]
Hi @davejuist 

- Once again, thanks for your feedback.
- The problem here seems to be the fact that Amasty module is saving an older instance of the order (one which status is still pending payment), while MultiSafepay module already processed an HTTP notification updating the order status. 
- Those cases in which you found the order is cancelled, we believe it`s because Magento will cancel a pending payment order after sometime (usually 8 hours by default). So, we believe those cases, even when the order is cancelled, the reason is the same, something in Amasty Checkout save a wrong and not fresh instance of the order. 
- As you said, it seems the issue previously we believe it was fixed in the latest release, is not exactly the same one.
- Maybe you can help us to investigate better this issue by using the following module: https://github.com/MultiSafepay/magento2-order-save-inspector
  - This module will log the stacktrace of any request putting the order in pending payment status. 
  - Enable debug mode in the MultiSafepay module is required. 
  - Once the issue happens again, we will be able to read which specific part of the code of Amasty Checkout is putting the order back to pending payment status and create a solution for it. 
- Also will be helpful to know exactly what are the settings configure in your shop, related to Amasty Checkout, which maybe  help us to reproduce the same issue.

**Comment by jordy2607** [comment]
Hi @vinodsowdagar @danielcivit 

FYI We believe we found our culprit. This specific shop has the module "mage_delight/utmtracker_module" installed.
This module has an observer which is triggered on the "checkout_onepage_controller_success_action" event.
During this observer a few custom fields are saved on the order. 

After disabling this part of the module, the issue we were having was no longer occurring. My assumption is that it's a timing issue where the order save from this observer is happening at the same time as the notification from Multisafepay is being handled. Where the order is fetched just before Multisafepay is updated the status. When the observer saves the order the status is being reset to the previous status, together with some other order fields.

@davejuist i'd suggest looking for some similar behaviour in your situation.

**Comment by davejuist** [comment]
@jordy2607 @vinodsowdagar , yes for us it`s a custom module from our side with the same issue. It has a observer on SaveOrderAfter which saves the order and is likely to cause the problem. In my case I changed the script to check if the order has been invoiced, and if so force the state on processing before saving. This solved it for us.
